### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by ivomarino** [strongloop/strong-pm#402]
I would like to run `strong-pm-container` via [Docker Compose](https://docs.docker.com/compose/), in order to define it in a `docker-compose.yml`, someone has already done this? And furthermore is it possible to enable Dockerized apps using the ` --driver docker` option also when running StrongLoop itself as a Docker container? Thanks.

**Comment by ivomarino** [comment]
seems to be running this way:

```
  strong-pm-container:
    image: strongloop/strong-pm
    container_name: strong-pm-container
    restart: always
    user: root
    ports:
      - "8701:8701"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --driver docker
```
